routes/web.php
            Route::get('delete/{id}', 'admin\PEAsController@destroy')->name('PEAs.delete');

            Route::get('/deleted', 'admin\PEAsController@PEAsDeleted')->name('PEAs.Deleted');
            Route::get('restore/{id}', 'admin\PEAsController@PEAsRestore')->name('PEAs.Restore');
        });


        Route::prefix('contract')->group(function () {
            Route::get('index', 'admin\contractsController@index')->name('contract.index');
            Route::get('create', 'admin\contractsController@create')->name('contract.create');

            Route::get('/', 'admin\contractsController@index')->name('contract.index');
            Route::get('/getActiveProjectMeasures', 'admin\contractsController@getActiveProjectMeasures')->name('contract.getActiveProjectMeasures');
            Route::post('store', 'admin\contractsController@store')->name('contract.store');
            Route::post('update', 'admin\contractsController@update')->name('contract.update');
            Route::get('show/{id}', 'admin\contractsController@show')->name('contract.show');
            Route::get('edit/{id}', 'admin\contractsController@edit')->name('contract.edit');
            Route::get('delete/{id}', 'admin\contractsController@destroy')->name('contract.delete');
            Route::get('contract/status/{id}/{status}', 'admin\contractsController@status')->name('contract.status');
            Route::get('create-project-budget', 'admin\contractsController@createProjectBudget')->name('contract.create.project.budget');
            Route::get('getActiveProjectMeasuresSelectedSubcategory', 'admin\contractsController@getActiveProjectMeasuresSelectedSubcategory')->name('contract.getActiveProjectMeasuresSelectedSubcategory');
            Route::get('/deleted', 'admin\contractsController@contractDeleted')->name('contract.contractDeleted');
            Route::get('restore/{id}', 'admin\contractsController@contractRestore')->name('contract.restore');
            Route::post('/contract/file/', 'admin\contractsController@contractFile')->name('contract.file.single');
            Route::post('/contract/file/create', 'admin\contractsController@contractFileCreate')->name('contract.file.single.create');
            Route::post('/contract/file/retain', 'admin\contractsController@contractFileRetain')->name('contract.file.retain.single');
            Route::post('/contract/file/retain/create', 'admin\contractsController@contractFileRetainCreate')->name('contract.file.retain.single.create');
            Route::get('file/delete', 'admin\contractsController@DeleteFile')->name('contract.file.delete');
            Route::get('file/delete/retain', 'admin\contractsController@DeleteFileRetain')->name('contract.file.retain.delete');

            Route::get('contract/checked/budget/project/measure/subcategory',
                'admin\contractsController@contractCheckedBudgetProjectMeasureSubcategory')
                ->name('contract.checked.budget.project.measure.subcategory');
            Route::get('contract/checked/budget/project/measure/subcategory/update',
                'admin\contractsController@ ')
                ->name('contract.checked.budget.project.measure.subcategory.update');
            Route::get('delete/contract/child/row', 'admin\contractsController@deleteContractChildRow')->name('delete.contract.child.row');

            Route::get('/contract/getFacilities', 'admin\contractsController@getFacilities')->name('contract.getFacilities');
        });

        Route::prefix('payment')->group(function () {
            Route::get('index', 'admin\paymentcontroller@index')->name('payment.index');
            Route::get('create', 'admin\paymentcontroller@create')->name('payment.create');
            Route::post('store', 'admin\paymentcontroller@store')->name('payment.store');


            Route::post('update/{id}', 'admin\paymentcontroller@update')->name('payment.update');
            Route::get('show/{id}', 'admin\paymentcontroller@show')->name('payment.show');
            Route::get('edit/{id}', 'admin\paymentcontroller@edit')->name('payment.edit');
            Route::get('delete/{id}', 'admin\paymentcontroller@destroy')->name('payment.delete');
            Route::get('get/contract', 'admin\paymentcontroller@getContract')->name('payment.get.contract');
            Route::get('status/{id}/{status}', 'admin\paymentcontroller@status')->name('payment.status');


            Route::get('/deleted', 'admin\paymentcontroller@paymentDeleted')->name('payment.paymentDeleted');
            Route::get('restore/{id}', 'admin\paymentcontroller@paymentRestore')->name('payment.restore');
            Route::get('contractors/contract', 'admin\paymentcontroller@GetContractorContracts')->name('payment.GetContractorContracts');
            Route::get('contract/details', 'admin\paymentcontroller@GetContractsDetails')->name('payment.GetContractsDetails');
            Route::get('contract/account/data', 'admin\paymentcontroller@GetAccountData')->name('payment.GetAccountData');
            Route::get('contract/projects', 'admin\paymentcontroller@getContractProjects')->name('payment.getContractProjects');
            Route::get('contract/projects/measure', 'admin\paymentcontroller@GetProjectMeasure')->name('payment.GetProjectMeasure');

            Route::get('contract/projects/measure/subcategory', 'admin\paymentcontroller@GetProjectMeasureSubcategory')->name('payment.GetProjectMeasureSubcategory');
            Route::get('calculate/budget', 'admin\paymentcontroller@calculateBudget')->name('payment.calculate.budget');

//files/
            Route::post('/supporting/documents/file', 'admin\paymentcontroller@supportingDocumentsFileSave')->name('supporting.documents.file.save');
            Route::get('supporting/documents/file', 'admin\paymentcontroller@supportingDocumentsFileDelete')->name('supporting.documents.file.delete');

            Route::post('payment/supporting/documents/file', 'admin\paymentcontroller@paymentSupportingDocumentsFileSave')->name('payment.supporting.documents.file.save');
            Route::get('payment/supporting/documents/file', 'admin\paymentcontroller@paymentSupportingDocumentsFileDelete')->name('payment.supporting.documents.file.delete');

            Route::post('payment/getFacilities', 'admin\paymentcontroller@getFacilities')->name('payment.getFacilities');

        });


        Route::prefix('user')->group(function () {
            Route::get('/', 'admin\userController@index')->name('user.index');
            Route::get('create', 'admin\userController@create')->name('user.create');
            Route::post('store', 'admin\userController@store')->name('user.store');
            Route::get('profile/{id}', 'admin\userController@profile')->name('user.profile');
            Route::get('edit/{id}', 'admin\userController@edit')->name('user.edit');
            Route::get('status/{id}', 'admin\userController@status')->name('user.status');
            Route::get('delete/{id}', 'admin\userController@destroy')->name('user.delete');
            Route::PATCH('update/{id}', 'admin\userController@update')->name('user.update');
        });


    });


    Route::get('/home', 'admin\adminController@index')->name('home');
    Route::resource('roles', 'RoleController');

//    Route::resource('users', 'UserController');


    Route::prefix('project')->group(function () {
        Route::get('/', 'admin\projectController@index')->name('project.index');
        Route::get('create', 'admin\projectController@create')->name('project.create');
        Route::get('/', 'admin\projectController@index')->name('project.index');
        Route::post('store', 'admin\projectController@store')->name('project.store');
        Route::post('update', 'admin\projectController@update')->name('project.update');
              Route::get('show/{id}/{flagScroll?}', 'admin\projectController@show')->name('project.show');

        Route::get('edit/{id}', 'admin\projectController@edit')->name('project.edit');
        Route::Post('delete/{id}', 'admin\projectController@destroy')->name('project.delete');

       Route::get('/deleted', 'admin\projectController@projectDeleted')->name('project.projectDeleted');
        Route::get('restore/{id}', 'admin\projectController@projectRestore')->name('project.restore');

        Route::get('project/status/{id}/{status}', 'admin\projectController@status')->name('project.status');
                Route::get('selected/province', 'admin\projectController@selectedProvince')->name('project.selected.province');
                        Route::post('/project/file/', 'admin\projectController@projectFile')->name('project.file.single');
        Route::get('delete/file/', 'admin\projectController@destroyFile')->name('project.delete.file');


        Route::get('delete/child/{projecthasprovince}', 'admin\projectController@deleteProjectChildRow');

         ///revised project route
        Route::get('revised-budget/{project_id?}/{line_reference_id?}', 'admin\projectController@revisedBudget')->name('project.revisedBudget');
        Route::Post('revised-budget/store', 'admin\projectController@revisedBudgetStore')->name('project.revisedBudgetStore');
        Route::get('revised-budget/status/{id}/{status}', 'admin\projectController@revisedbudgetstatus')->name('project.revisedBudgetStatus');

//project history
        Route::get('history/list/{historyList}', 'admin\projectController@historyList')->name('project.history.list');
        Route::get('history/show/{id}/{project_id}', 'admin\projectController@historyShow')->name('project.history.show');


//        project check bugdet value
        Route::get('history/list/{historyList}', 'admin\projectController@historyList')->name('project.history.list');
        Route::get('check/defining/budget/contract', 'admin\projectController@CheckDefiningBudgetContract')->name('project.check.defining.budget.contract');

app/Http/Controllers/RoleController.php
<?php


namespace App\Http\Controllers;


use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use DB;


class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
//    function __construct()
//    {
//        $this->middleware('permission:role-list|role-create|role-edit|role-delete', ['only' => ['index','store']]);
//        $this->middleware('permission:role-create', ['only' => ['create','store']]);
//        $this->middleware('permission:role-edit', ['only' => ['edit','update']]);
//        $this->middleware('permission:role-delete', ['only' => ['destroy']]);
//    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $roles = Role::orderBy('id', 'DESC')->paginate(5);
        return view('admin.roles.index', ['roles'=>$roles]);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permission = Permission::orderBy('name')->get();

        return view('admin.roles.create', compact('permission'));
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:roles,name',
            'permission' => 'required',
        ]);


        $role = Role::create(['name' => $request->input('name')]);
        $role->syncPermissions($request->input('permission'));


        return redirect()->route('roles.index')
            ->with('success', 'Role created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $role = Role::find($id);
        $permission = Permission::get();
        $rolePermissions = DB::table("role_has_permissions")->where("role_has_permissions.role_id", $id)
            ->pluck('role_has_permissions.permission_id', 'role_has_permissions.permission_id')
            ->all();

        return view('admin.roles.show',  compact('role', 'permission', 'rolePermissions'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Role::find($id);
        $permission = Permission::get();
        $rolePermissions = DB::table("role_has_permissions")->where("role_has_permissions.role_id", $id)
            ->pluck('role_has_permissions.permission_id', 'role_has_permissions.permission_id')
            ->all();


        return view('admin.roles.edit', compact('role', 'permission', 'rolePermissions'));
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'permission' => 'required',
        ]);


        $role = Role::find($id);
        $role->name = $request->input('name');
        $role->save();


        $role->syncPermissions($request->input('permission'));


        return redirect()->route('roles.index')
            ->with('success', 'Role updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        DB::table("roles")->where('id', $id)->delete();
        return redirect()->route('roles.index')
            ->with('success', 'Role deleted successfully');
    }
}

resources/views/admin/roles/index.blade.php
@extends('admin.layout.index')
@section('content')
    <section class="bg-primary content-header"
             style="background-color:#ffc533 !important; padding-bottom: 10px; margin-top: 10px;padding-left: 10px;">
        <div class="row">
            <div class="col-8">
                <h1>Roles</h1>
            </div>
            <div class="col-4">
                <ol class="breadcrumb" style="color:#444;float: right">
                    <li>
                        <i class="fa fa-dashboard"></i> Dashboard &nbsp;
                    </li>
                    <li>
                        <i class="fa fa-angle-right" style="color: #ccc;"></i> Roles &nbsp;
                    </li>

                </ol>
            </div>
        </div>
    </section>
    <div class="clearfix mt-3">
            @can('role-create')
                <a href="{{ route('roles.create') }}" class="btn btn-success btn-flat float-left">
                    <i class="fa fa-plus"></i> Create New Role
                </a>
            @endcan
        </div>
    </div>
    <div class="container-fluid" style="margin-top: 10px">
        <div class="card">

            <div class="card-body">


                    <div class="row">
                        <div class="col-sm-12">

                             <table id="role_table" class="table-bordered table-hover dataTable dtr-inline">
                                <thead>
                                <tr>
                                    <th style="width:10%;text-align: center">ID</th>
                                    <th>Name</th>
                                    <th width="20%" style="text-align: center">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($roles as $key => $role)
                                    <tr>
                                        <td style="text-align: center">{{ ++$key}}</td>
                                        <td>{{ucfirst( $role->name) }}</td>
                                        <td style="text-align: center">
                                            <a class="btn btn-info" href="{{ route('roles.show',$role->id) }}">Show</a>
                                            @can('role-edit')
                                                <a class="btn btn-primary" href="{{ route('roles.edit',$role->id) }}">Edit</a>
                                            @endcan
                                            @can('role-delete')
                                                <form method='Post' action="{{route('roles.destroy', $role->id)}}"
                                                      style="display:inline">
                                                    @method('DELETE')
                                                    @csrf
                                                    @if($role->name!=='Admin')
                                                        <button type="submit" class="btn btn-danger">Delete</button>
                                                    @endif
                                                </form>
                                            @endcan
                                        </td>
                                    </tr>

                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>
            </div>
            <!-- /.card-body -->
        </div>

    @endsection